name: "jjversion-action"
description: "Creates a version for the repository using jjversion"
author: "jjliggett"
branding:
  icon: "tag"
  color: "blue"
inputs:
  skip-go-installation:
    description: "If set to true, then the action uses pre-installed Go"
    default: "false"
    required: false
outputs:
  major:
    description: "Major version"
    value: ${{ steps.jjversion.outputs.major }}
  minor:
    description: "Minor version" 
    value: ${{ steps.jjversion.outputs.minor }}
  patch:
    description: "Patch version"
    value: ${{ steps.jjversion.outputs.patch }}
  majorMinorPatch:
    description: "MajorMinorPatch version"
    value: ${{ steps.jjversion.outputs.majorMinorPatch }}
  sha:
    description: "Commit Sha"
    value: ${{ steps.jjversion.outputs.sha }}
  shortSha:
    description: "ShortSha"
    value: ${{ steps.jjversion.outputs.shortSha }}

runs:
  using: "composite"
  steps:
    - run: echo "Setting up go"
      shell: pwsh
      if: ${{ inputs.skip-go-installation != 'true' }}
    - run: echo "Skipping go setup"
      shell: pwsh
      if: ${{ inputs.skip-go-installation == 'true' }}
    - name: Setup Go unless skip-go-installation is true
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
      if: ${{ inputs.skip-go-installation != 'true' }}
    - run: mkdir jjversion
      shell: pwsh
      working-directory: ${{ runner.temp }}
    - run: go mod init local
      shell: pwsh
      working-directory: ${{ runner.temp }}/jjversion
    - run: go get -v -d github.com/jjliggett/jjversion-gha-output@9c0f517e6b33bae4c09f69b453a7929fada44f94
      shell: pwsh
      working-directory: ${{ runner.temp }}/jjversion
    - run: ls "$(go env GOPATH)/pkg/mod/github.com/jjliggett"
      shell: pwsh
    - run: |
        cd "$(go env GOPATH)/pkg/mod/github.com/jjliggett"
        if ($env:RUNNER_OS -eq "Windows")
        {
          cd jjversion-gha-output*
          echo "Building jjversion-gha-output"
          go build -o jjversion-gha-output.exe
        } else {
          ls -al
          chmod +w jjversion-gha-output*
          ls -al
          cd jjversion-gha-output*
          echo "Building jjversion-gha-output"
          go build -a -v -o jjversion-gha-output
          cp jjversion-gha-output $env:GITHUB_WORKSPACE/jjversion-gha-output
        }
      shell: pwsh
    - run: |
        if ($env:RUNNER_OS -eq "Windows")
        {
          cp "$(go env GOPATH)/pkg/mod/github.com/jjliggett/jjversion-gha-output*/jjversion-gha-output.exe" .
        }
      shell: pwsh
    - run: printenv
      shell: pwsh
    - run: |
        if ($env:RUNNER_OS -eq "Windows")
        {
          ./jjversion-gha-output.exe
        } else {
          ./jjversion-gha-output
        }
      id: jjversion
      shell: pwsh
    - name: Display version outputs
      run: |
        echo "Major: ${{ steps.jjversion.outputs.major }}"
        echo "Minor: ${{ steps.jjversion.outputs.minor }}"
        echo "Patch: ${{ steps.jjversion.outputs.patch }}"
        echo "MajorMinorPatch: ${{ steps.jjversion.outputs.majorMinorPatch }}"
        echo "Sha: ${{ steps.jjversion.outputs.sha }}"
        echo "ShortSha: ${{ steps.jjversion.outputs.shortSha }}"
      shell: pwsh
    - run: |
        if ($env:RUNNER_OS -eq "Windows")
        {
          rm ./jjversion-gha-output.exe
        } else {
          rm ./jjversion-gha-output
        }
      shell: pwsh
